# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: BuildLLVMJob
  timeoutInMinutes: 0
  pool:
    vmImage: macOS-10.15

  steps:

  - script: |
      wget https://github.com/light-tech/LLVM-On-iOS/releases/download/libffi_v3.3plus/libffi.tar.xz
      tar xzf libffi.tar.xz
      test -d libffi && echo "libffi was successfully extracted"
      git clone --single-branch --branch release/11.x https://github.com/llvm/llvm-project.git
      ./build-llvm.sh macOS
    displayName: 'Checkout and build llvm project'

  - script: |
      PLATFORM="macOS"
      ./prepare-llvm.sh $PLATFORM
      tar -cJf LLVM.tar.xz LLVM-$PLATFORM/
    displayName: 'Packaging LLVM build'

  - publish: $(System.DefaultWorkingDirectory)/llvm-project/build_ios/CMakeCache.txt
    artifact: CMakeOutputs
    displayName: 'Publish CMake output for inspection'
    enabled: false

  - publish: $(System.DefaultWorkingDirectory)/LLVM.tar.xz
    artifact: LLVM
    displayName: 'Publish LLVM Libs'
    enabled: true
