# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: BuildLLVMJob
  timeoutInMinutes: 0
  pool:
    vmImage: macOS-latest

  steps:

  - script: |
      # Download and extract ninja
      wget https://github.com/ninja-build/ninja/releases/download/v1.10.2/ninja-mac.zip
      unzip ninja-mac.zip
      # Download various tools such as autoconf, automake and libtool
      wget https://github.com/light-tech/LLVM-On-iOS/releases/download/llvm12.0.0/tools.tar.xz
      tar xzf tools.tar.xz
      mv ninja tools/bin
      export PATH=$PATH:`pwd`/tools/bin
      ./build-llvm-framework.sh maccatalyst iphoneos iphonesimulator
    displayName: 'Checkout and build llvm framework'
    enabled: true
    continueOnError: true

  - publish: $(System.DefaultWorkingDirectory)
    artifact: AllFiles
    displayName: 'Publish all files for inspection'
    enabled: false

  - publish: $(System.DefaultWorkingDirectory)/LLVM.xcframework.tar.xz
    artifact: LLVM.xcframework
    displayName: 'Publish LLVM XCFramework'
    enabled: true

  - publish: $(System.DefaultWorkingDirectory)/libclang.tar.xz
    artifact: Clang-Headers
    displayName: 'Publish LLVM Clang Headers'
    enabled: true
