# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: BuildLLVMJob
  timeoutInMinutes: 0
  pool:
    vmImage: macOS-10.15

  steps:

  - script: ./build-llvm-framework.sh
    displayName: 'Checkout and build llvm project'

  - publish: $(System.DefaultWorkingDirectory)/llvm-project/build
    artifact: CMakeOutputs
    displayName: 'Publish CMake output for inspection'
    enabled: false

  - publish: $(System.DefaultWorkingDirectory)/LLVM.xcframework
    artifact: LLVM
    displayName: 'Publish LLVM XCFramework'
    enabled: true

  - publish: $(System.DefaultWorkingDirectory)/LLVM-iOS.tar.xz
    artifact: LLVM-iOS
    displayName: 'Publish LLVM iOS Lib'
    enabled: true

  - publish: $(System.DefaultWorkingDirectory)/LLVM-macOS.tar.xz
    artifact: LLVM-macOS
    displayName: 'Publish LLVM macOS Lib'
    enabled: true
