# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macOS-10.15

steps:

- script: |
    wget https://github.com/light-tech/LLVM-On-iOS/releases/download/libffi_v3.3plus/libffi.tar.xz
    tar xzf libffi.tar.xz
    test -d libffi && echo "libffi was successfully extracted"
    git clone  --single-branch --branch release/11.x https://github.com/llvm/llvm-project.git
    ./buildllvm-iOS.sh
  displayName: 'Checkout and build llvm project'

- publish: $(System.DefaultWorkingDirectory)/llvm-project/build_ios/CMakeCache.txt
  artifact: CMakeOutputs
  displayName: 'Publish CMake output for inspection'
  enabled: true

- publish: $(System.DefaultWorkingDirectory)/LLVM-iOS
  artifact: LLVM
  displayName: 'Publish LLVM Libs'
  enabled: false
