# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: macOS-10.15

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: |
    LIBFFI=`pwd`
    git clone https://github.com/libffi/libffi.git
    cd libffi
    xcodebuild -list
    xcodebuild -scheme libffi-iOS SYMROOT="$LIBFFI"
    #git clone https://github.com/llvm/llvm-project.git
    #cd llvm-project
    #../buildllvm-iOS.sh
  displayName: 'Checkout and build libffi'
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
