# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: BuildLLVMJob
  timeoutInMinutes: 0
  pool:
    vmImage: macOS-10.15

  steps:

  - script: ./build-llvm-framework.sh maccatalyst # iphoneos iphonesimulator
    displayName: 'Checkout and build llvm framework'
    enabled: true

  - publish: $(System.DefaultWorkingDirectory)
    artifact: AllFiles
    displayName: 'Publish all files for inspection'
    enabled: false
    continueOnError: true

  - publish: $(System.DefaultWorkingDirectory)/LLVM.xcframework.tar.xz
    artifact: LLVM.xcframework
    displayName: 'Publish LLVM XCFramework'
    enabled: true

  - publish: $(System.DefaultWorkingDirectory)/Lib-Clang-iphoneos.tar.xz
    artifact: Clang-Headers
    displayName: 'Publish LLVM Clang Headers'
    enabled: true
